name: Tests

on:
  push:
    branches: [main, tests]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Install depedencies
        run: chmod +x install.sh && ./install.sh

      - name: Run tests
        run: make check
