name: Tests

on:
  push:
    branches: [main, tests]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install depedencies
        run: bash install.sh

      - name: Run tests
        run: make check
